//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWebsite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.ArticleCategorySubjects = new HashSet<ArticleCategorySubject>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public long ArticleBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsPublished { get; set; }
        public bool IsActive { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<ArticleCategorySubject> ArticleCategorySubjects { get; set; }
    }
}
