//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWebsite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleCategorySubject
    {
        public long Id { get; set; }
        public long ArticleId { get; set; }
        public int CategoryId { get; set; }
        public long SubjectId { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Category Category { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
