
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SampleWebsite.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Comment
{

    public Comment()
    {

        this.Comments1 = new HashSet<Comment>();

    }


    public long Id { get; set; }

    public Nullable<long> ParentId { get; set; }

    public Nullable<long> QuestionId { get; set; }

    public Nullable<long> AnswerId { get; set; }

    public string Description { get; set; }

    public int Createdby { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public Nullable<int> ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public bool IsActive { get; set; }



    public virtual Answer Answer { get; set; }

    public virtual ICollection<Comment> Comments1 { get; set; }

    public virtual Comment Comment1 { get; set; }

    public virtual Question Question { get; set; }

}

}
