
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SampleWebsite.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Question
{

    public Question()
    {

        this.Answers = new HashSet<Answer>();

        this.Comments = new HashSet<Comment>();

    }


    public long Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int Status { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime CreatedDate { get; set; }



    public virtual ICollection<Answer> Answers { get; set; }

    public virtual ICollection<Comment> Comments { get; set; }

}

}
