//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWebsite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.QuestionAnswers = new HashSet<QuestionAnswer>();
            this.QuestionCategorySubjects = new HashSet<QuestionCategorySubject>();
        }
    
        public long Id { get; set; }
        public string Description { get; set; }
        public long QuestionBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsPublished { get; set; }
        public bool IsActive { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<QuestionAnswer> QuestionAnswers { get; set; }
        public virtual ICollection<QuestionCategorySubject> QuestionCategorySubjects { get; set; }
    }
}
