

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SampleWebsite.Data
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class SampleEntities : DbContext
{
    public SampleEntities()
        : base("name=SampleEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<User> Users { get; set; }

    public DbSet<UserType> UserTypes { get; set; }

    public DbSet<Answer> Answers { get; set; }

    public DbSet<Article> Articles { get; set; }

    public DbSet<ArticleTechnology> ArticleTechnologies { get; set; }

    public DbSet<ArticleType> ArticleTypes { get; set; }

    public DbSet<Comment> Comments { get; set; }

    public DbSet<Question> Questions { get; set; }

    public DbSet<Status> Status { get; set; }

    public DbSet<sysdiagram> sysdiagrams { get; set; }

    public DbSet<Technology> Technologies { get; set; }

}

}

