//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWebsite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.ArticleCategorySubjects = new HashSet<ArticleCategorySubject>();
            this.QuestionCategorySubjects = new HashSet<QuestionCategorySubject>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
        public int CategoryId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<ArticleCategorySubject> ArticleCategorySubjects { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<QuestionCategorySubject> QuestionCategorySubjects { get; set; }
    }
}
