//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWebsite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Answers = new HashSet<Answer>();
            this.Articles = new HashSet<Article>();
            this.Questions = new HashSet<Question>();
        }
    
        public long Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int UserTypeId { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ICollection<Article> Articles { get; set; }
        public virtual UserType UserType { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
    }
}
